# Generated by Django 5.2.17 on 2026-10-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactrequest",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="event",
            name="agenda",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="event",
            name="meeting_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="modality",
            field=models.CharField(
                choices=[
                    ("in_person", "Presencial"),
                    ("virtual", "Virtual"),
                    ("hybrid", "Híbrida"),
                ],
                default="in_person",
                max_length=20,
            ),
        ),
    ]
