# Generated by Django 5.2.17 on 2026-10-05 07:29

import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


def create_site_profile(apps, schema_editor):
    SiteProfile = apps.get_model("portal", "SiteProfile")
    SiteProfile.objects.using(schema_editor.connection.alias).get_or_create(key="main")


class Migration(migrations.Migration):

    dependencies = [
        (
            "portal",
            "0002_contactrequest_phone_event_agenda_event_meeting_link_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("alt_text", models.CharField(blank=True, max_length=240)),
                ("file", models.FileField(upload_to=portal.models.content_asset_path)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_assets_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="image_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="portal.contentasset",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="assets",
            field=models.ManyToManyField(
                blank=True, related_name="publications", to="portal.contentasset"
            ),
        ),
        migrations.CreateModel(
            name="SiteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(default="main", max_length=40, unique=True)),
                (
                    "name",
                    models.CharField(
                        default="Mesa de Competitividad de Quetzaltenango",
                        max_length=180,
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=500)),
                ("mission", models.TextField(blank=True)),
                ("vision", models.TextField(blank=True)),
                ("objectives", models.JSONField(blank=True, default=list)),
                ("represented_sectors", models.JSONField(blank=True, default=list)),
                ("work_framework", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "banner_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="banner_sites",
                        to="portal.contentasset",
                    ),
                ),
                (
                    "logo_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logo_sites",
                        to="portal.contentasset",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="site_profiles_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.RunPython(create_site_profile, migrations.RunPython.noop),
    ]
