# Generated by Django 5.2.17 on 2026-10-05 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "responsibility",
                    models.CharField(default="Seguimiento", max_length=120),
                ),
                ("starts_at", models.DateField()),
                ("ends_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_assignments",
                        to="directory.member",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ends_at__isnull", True),
                            ("ends_at__gte", models.F("starts_at")),
                            _connector="OR",
                        ),
                        name="project_assignment_dates_valid",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("ends_at__isnull", True)),
                        fields=("project", "member"),
                        name="one_active_project_assignment",
                    ),
                ],
            },
        ),
    ]
