# Generated by Django 5.2.17 on 2026-10-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_projectassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="confidentiality",
            field=models.CharField(
                choices=[
                    ("public", "Público"),
                    ("internal", "Interno"),
                    ("temporary_confidential", "Confidencial temporal"),
                ],
                default="internal",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="confidentiality",
            field=models.CharField(
                choices=[
                    ("public", "Público"),
                    ("internal", "Interno"),
                    ("temporary_confidential", "Confidencial temporal"),
                ],
                default="internal",
                max_length=32,
            ),
        ),
    ]
