# Generated by Django 5.2.17 on 2026-10-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
        ("meetings", "0002_minute_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="invited_members",
            field=models.ManyToManyField(
                blank=True, related_name="meeting_invitations", to="directory.member"
            ),
        ),
    ]
