# Generated by Django 5.2.17 on 2026-10-05 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("directory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Voting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("scheduled", "Programada"),
                            ("open", "Abierta"),
                            ("closed", "Cerrada"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        default=list,
                        help_text="Lista configurable de opciones; quórum y reglas de aprobación quedan pendientes.",
                    ),
                ),
                ("opens_at", models.DateTimeField(blank=True, null=True)),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "commission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votings",
                        to="directory.commission",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(max_length=120)),
                ("cast_at", models.DateTimeField(auto_now_add=True)),
                ("client_request_id", models.UUIDField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votes",
                        to="directory.member",
                    ),
                ),
                (
                    "voting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votes",
                        to="voting.voting",
                    ),
                ),
            ],
            options={
                "ordering": ["cast_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="voting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closes_at__isnull", True),
                    ("opens_at__isnull", True),
                    ("closes_at__gt", models.F("opens_at")),
                    _connector="OR",
                ),
                name="voting_close_after_open",
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("voting", "member"), name="one_vote_per_member_per_voting"
            ),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_request_id__isnull", False)),
                fields=("voting", "client_request_id"),
                name="one_voting_request_id",
            ),
        ),
    ]
