# Generated by Django 5.2.17 on 2026-10-05 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0003_meeting_invited_members"),
        ("projects", "0002_projectassignment"),
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voting",
            name="agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="votings",
                to="meetings.agreement",
            ),
        ),
        migrations.AddField(
            model_name="voting",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="votings",
                to="projects.project",
            ),
        ),
    ]
