# Generated by Django 5.2.17 on 2026-10-05 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
        ("meetings", "0003_meeting_invited_members"),
        ("projects", "0003_alter_document_confidentiality_and_more"),
        ("voting", "0002_voting_agreement_voting_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="voting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("agreement__isnull", True), ("project__isnull", False)),
                    models.Q(("agreement__isnull", False), ("project__isnull", True)),
                    _connector="OR",
                ),
                name="voting_exactly_one_subject",
            ),
        ),
    ]
