# Generated by Django 5.2.17 on 2026-10-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="actor_roles",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
